import { Portfolio } from './interfaces/portfolio';

export const PORTFOLIOS: Portfolio[] = [
  {
    _id: 1,
    title: 'project_title_1',
    category: 'WEB',
    description: 'project_desc_1',
    preview: 'assets/img/portfolio/installation_prev.png',
    image: 'assets/img/portfolio/installation.png',
    date: '09/07/2023',
  },
  {
    _id: 2,
    title: 'project_title_2',
    category: 'WEB',
    description: 'project_desc_2',
    preview: 'assets/img/portfolio/calendar-airnbnb_prev.png',
    image: 'assets/img/portfolio/calendar-airnbnb.jpg',
    date: '30/07/2022',
  },
  {
    _id: 3,
    title: 'project_title_3',
    category: 'WEB',
    description: 'project_desc_3',
    preview: 'assets/img/portfolio/export-whatsapp_prev.png',
    image: 'assets/img/portfolio/export-whatsapp.jpg',
    date: '07/06/2022',
  },
  {
    _id: 4,
    title: 'project_title_4',
    category: 'WEB',
    description: 'project_desc_4',
    preview: 'assets/img/portfolio/laravel-mail-markdown_prev.png',
    image: 'assets/img/portfolio/laravel-mail-markdown.jpg',
    date: '03/04/2022',
  },
  {
    _id: 5,
    title: 'project_title_5',
    category: 'WEB',
    description: 'project_desc_5',
    preview: 'assets/img/portfolio/coding_prev.png',
    image: 'assets/img/portfolio/coding.jpg',
    date: '02/04/2022',
  },
  {
    _id: 6,
    title: 'project_title_6',
    category: 'SEO',
    description: 'project_desc_6',
    preview: 'assets/img/portfolio/shotz_prev.png',
    image: 'assets/img/portfolio/shotz.png',
    url: 'https://shotzfilm.de/',
  },
  {
    _id: 7,
    title: 'project_title_7',
    category: 'WEB',
    description: 'project_desc_7',
    preview: 'assets/img/portfolio/klav_prev.png',
    image: 'assets/img/portfolio/klav.png',
    url: 'https://www.outilsobdfacile.fr/',
  },
  {
    _id: 8,
    title: 'project_title_8',
    category: 'WEB',
    description: 'project_desc_8',
    preview: 'assets/img/portfolio/creative_prev.png',
    image: 'assets/img/portfolio/creative.png',
    url: 'https://www.creative-cables.be/nl/',
  },
  {
    _id: 9,
    title: 'project_title_9',
    category: 'WEB',
    description: 'project_desc_9',
    preview: 'assets/img/portfolio/kris_prev.png',
    image: 'assets/img/portfolio/kris.png',
    url: 'https://kristranslation.com/?v=947d7d61cd9a',
  },
  {
    _id: 10,
    title: 'project_title_10',
    category: 'MOBILE',
    description: 'project_desc_9',
    preview: 'assets/img/portfolio/fly_prev.png',
    image: 'assets/img/portfolio/fly.jpg',
    date: '02/2024',
  },
];
